<?php

    $en =  array(
        'main.menu'=>'Main',
        'documents.menu'=>'Documents',
        'nANDu.menu'=>'News and updates',
        'reg.menu'=>'Registre',
        'account.menu'=>'Account',
        'list.docs'=>'Document`s list',
        'example.doc'=>'Show Example',
        'doc1.docs'=>'Accrual of social scholarship',
        //here all the rest docs must be!!!!
        'create.docs'=>'Create',
        'goSignIn.reg'=>'Allready have an account?',
        'signInLink'=>'Sign in',
        //'ur.acc'=>'Your account',
        'history.acc'=>'Documents history',
        'download.acc'=>'Download',
        'sign.acc'=>'Sign the document',
        'out.acc'=>'Log out',
        'errorRegEmptyMail'=>"mail field can't be empty",
        'errorRegEmptyName'=>"username field can't be empty",
        'errorRegEmptyPass'=>"password field can't be empty",
        'errorRegDomain'=>"Sorry but you can't use any othe e-mails except your corporate mail addres that ends on '@infiz.khpi.edu.ua'. We are working on adding more domains in future updates",
        'errorRegununiqName'=>"Such username is allready using",
        'errorRegununiqMail'=>"Such e-mail address is allready using",
        'okMsg'=>"OK",
        'errorSignIn'=>"WRONG USERNAME OR PASSWORD",
        'Msghistory'=>"Empty document's history",
        'Msgdwn'=>"No documents to download",
        'Msgsign'=>"No documents to sign",
        'show_docError'=>"Such file doesn't exist",
        'sign_documentError'=>'Filetype must be only PNG',
        'sign_documentMsg'=>"Document was signed",
        'deleteDocError1'=>'No such document',
        'deleteDocError2'=>"This file doesn't exist",
        'deleteDocMsg'=>'Document was deleted',
        'docError1'=>'You must fill all the fields',
        'docError2'=>"You can't send documents to yourself",
        'docError3'=>"You must fill the textarea field",
        'docError4'=>"You must add your signature",
        'docError5'=>'Filetype must be only PNG',
        'wrongRecipient'=>"There is no such user who you are trying to send this document",
        'docMsg'=>"Your document was generated and sended to recipient to sign it",
        'goHome'=>'Take me back home'

    );

    $ua =  array(
        'main.menu'=>'Головна',
        'documents.menu'=>'Документи',
        'nANDu.menu'=>'Новини та оновлення',
        'reg.menu'=>'Зареєструватися',
        'account.menu'=>'Акаунт',
        'list.docs'=>'Список документів',
        'example.doc'=>'Переглянути приклад',
        'doc1.docs'=>'Accrual of social scholarship',
        //here all the rest docs must be!!!!
        'create.docs'=>'Створити',
        'goSignIn.reg'=>'Вже є маєте акаунт?',
        'signInLink'=>'Увійти',
        //'ur.acc'=>'Ваш акаунт',
        'history.acc'=>'Історія документів',
        'download.acc'=>'Завантажити',
        'sign.acc'=>'Підписати документи',
        'out.acc'=>'Вийти',
        'errorRegEmptyMail'=>"Поле mail не може бути порожнім",
        'errorRegEmptyName'=>"Поле username не може бути порожнім",
        'errorRegEmptyPass'=>"Поле password не може бути порожнім",
        'errorRegDomain'=>"Перепрошуємо, але Ви не можете використовувати ніякі поштові адреси окрім корпоративної, що має домен '@infiz.khpi.edu.ua'. Ми працюємо над тим, щоб додати більше доменів у майбутньому",
        'errorRegununiqName'=>"Користувач з таким іменем вже існує",
        'errorRegununiqMail'=>"Користувач з такою поштою вже існує",
        'okMsg'=>"OK",
        'errorSignIn'=>"Неправильні ім'я користувача або пароль",
        'Msghistory'=>"Істрія документів пуста",
        'Msgdwn'=>"Немає документів для завантаження",
        'Msgsign'=>"Немає документів для підпису",
        'show_docError'=>"Такого файлу не існує",
        'sign_documentError'=>'Тип файлу може бути ТІЛЬКИ PNG',
        'sign_documentMsg'=>"Документ було підписано",
        'deleteDocError1'=>'Такого документу не існує',
        'deleteDocError2'=>"Такого документу не існує",
        'deleteDocMsg'=>'Документ було видалено',
        'docError1'=>'Ви маєте заповнити усі поля',
        'docError2'=>"Ви не можете надсилати документ самі собі",
        'docError3'=>"Ви маєте заповнити поле для тексту заяви",
        'docError4'=>"Ви маєте додати свій підпис",
        'docError5'=>'Тип файлу міє бути ТІЛЬКИ PNG',
        'wrongRecipient'=>"Користувача, якому ви намагаєтесь надіслати документ НЕ існує",
        'docMsg'=>"Ваш документ було створено і надіслано отримувасу для підписання",
        'goHome'=>'На головну'
    );

?>